[workspace]
resolver = "3"
members = ["itemize", "itemize_derive", "itemize_derive_impl"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Pingid/itemize"
authors = ["Dan Beaven"]
