[package]
name = "itemize"
version = "0.1.0"
edition = "2024"

[dependencies]
itemize_derive = { path = "../itemize_derive", optional = true }

[features]
default = ["derive"]
derive = ["itemize_derive"]
